language: python
python:
    - "3.4"
    - "3.5"
install:
    - pip install -r requirements/development.txt
script:
    - pep8 fastblog/
    - python fastblog/manage.py test bitly fastblog posts users -v2
notifications:
    slack: pn101:gRAIEHfMDfA6AZ9Hz28aC4e3
