# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bitlink',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
