# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitly', '0002_bitlinklog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitlinklog',
            old_name='request_addr',
            new_name='remote_addr',
        ),
    ]
