# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitly', '0003_bitlinklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitlinklog',
            name='http_meta_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
