# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitly', '0003_auto_20160617_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitlinklog',
            old_name='http_referr',
            new_name='http_referer',
        ),
    ]
