# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160619_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signup_sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
