# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_signup_sms_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_phonenumber_exists',
            field=models.BooleanField(default=False),
        ),
    ]
